=== Politecnico-JIC2/Ejercicio3_ProductosComputador/ProductosComputador.dtd
<!ELEMENT Productos (Producto+)>
        <!ELEMENT Producto (Raton|Teclado|Monitor)>
        <!ELEMENT Raton (Codigo,Nombre?,Descripcion?)>
        <!ELEMENT Teclado (Codigo,Nombre?,Descripcion?)>
        <!ELEMENT Monitor (Codigo,Nombre?,Descripcion?)>
        <!ELEMENT Codigo (#PCDATA)>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT Descripcion (#PCDATA)>

=== Politecnico-JIC2/Ejercicio3_ProductosComputador/ProductosComputador.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="ProductosComputador.xsl" ?>
<!DOCTYPE Productos SYSTEM "ProductosComputador.dtd">
<Productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="ProductosComputador.xsd">
    <Producto>
        <Raton>
            <Codigo>C0001</Codigo>
            <Nombre>RA450</Nombre>
            <Descripcion>Ligero</Descripcion>
        </Raton>
    </Producto>
    <Producto>
        <Teclado>
            <Codigo>C0002</Codigo>
            <Nombre>KEY300</Nombre>
        </Teclado>
    </Producto>
    <Producto>
        <Monitor>
            <Codigo>C0003</Codigo>
            <Descripcion>FÃ¡cil de usar</Descripcion>
        </Monitor>
    </Producto>
    <Producto>
        <Raton>
            <Codigo>C0004</Codigo>
        </Raton>
    </Producto>

</Productos>
